# Generated by Django 2.2.3 on 2019-07-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('choices', models.CharField(choices=[('About', 'About'), ('Phone', 'Phone'), ('Email', 'Email')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
