# Generated by Django 2.2.3 on 2019-07-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190710_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='choices',
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(choices=[('About', 'About'), ('Phone', 'Phone'), ('Email', 'Email')], max_length=50),
        ),
    ]
