# Generated by Django 2.2.3 on 2019-07-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20190710_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(choices=[('Home', 'Home'), ('Phone', 'Phone'), ('Email', 'Email'), ('Products', 'Products'), ('About', 'About')], max_length=50),
        ),
    ]
